@echo off
echo Baixando o AnyDesk...
powershell -Command "Invoke-WebRequest -Uri 'https://download.anydesk.com/AnyDesk.exe' -OutFile 'C:\AnyDesk.exe'"
echo Instalando o AnyDesk silenciosamente...
C:\AnyDesk.exe --install "C:\Program Files (x86)\AnyDesk" --start-with-win --create-shortcuts --create-desktop-icon --silent
echo Aguardando o servico iniciar...
timeout /t 5 /nobreak > nul
echo Configurando a senha 1234 para acesso autonomo...
echo 1234 | "C:\Program Files (x86)\AnyDesk\AnyDesk.exe" --set-password
echo AnyDesk instalado e configurado com sucesso!
